//ActionTypes for Product data
export const PRODUCT_DATA_CREATE = "PRODUCT_DATA_CREATE";
export const PRODUCT_DATA_FETCHED = "PRODUCT_DATA_FETCHED";
export const PRODUCT_DATA_LOADING = "PRODUCT_DATA_LOADING";
export const PRODUCT_DATA_FAILED = "PRODUCT_DATA_FAILED";
// export const PRODUCT_DATA_SUCCESS = "PRODUCT_DATA_SUCCESS";

//ActionTypes for Location data
export const LOCATION_DATA_FETCHED = "LOCATION_DATA_FETCHED";
export const LOCATION_DATA_LOADING = "LOCATION_DATA_LOADING";
export const LOCATION_DATA_FAILED = "LOCATION_DATA_FAILED";
// export const LOCATION_DATA_SUCCESS = "LOCATION_DATA_SUCCESS";

//ActionTypes for Location data
export const PRODMOV_DATA_FETCHED = "PRODMOV_DATA_FETCHED";
export const PRODMOV_DATA_LOADING = "PRODMOV_DATA_LOADING";
export const PRODMOV_DATA_FAILED = "PRODMOV_DATA_FAILED";
// export const PRODMOV_DATA_SUCCESS = "PRODMOV_DATA_SUCCESS";
